apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: vamsikrishnak123
    provider: github
    repository: php-helloworld
  name: vamsikrishnak123-php-helloworld
spec:
  description: Imported application for vamsikrishnak123/php-helloworld
  httpCloneURL: https://github.com/vamsikrishnak123/php-helloworld.git
  org: vamsikrishnak123
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: php-helloworld
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/vamsikrishnak123/php-helloworld.git
